<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-common/src', $vendorDir . '/phpdocumentor/reflection-docblock/src', $vendorDir . '/phpdocumentor/type-resolver/src'),
    'Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Sober\\Models\\Model\\' => array($vendorDir . '/soberwp/models/src/Model'),
    'Sober\\Models\\' => array($vendorDir . '/soberwp/models/src'),
    'Saltus\\WP\\Plugin\\Saltus\\Framework\\Tests\\' => array($baseDir . '/tests'),
    'Saltus\\WP\\Plugin\\Saltus\\Framework\\' => array($baseDir . '/src'),
    'Noodlehaus\\' => array($vendorDir . '/hassankhan/config/src'),
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
);
