<?php

namespace Saltus\WP\Framework\Tests\Features;

use Saltus\WP\Framework\Features\AiAssistant\AiAssistantProvider;
use Saltus\WP\Framework\Modeler;
use Saltus\WP\Framework\Models\Model;
use Saltus\WP\Framework\Rest\AiAssistantController;
use Saltus\WP\Framework\Rest\ModelRestPolicy;
use Saltus\WP\Framework\Tests\TestCase;

require_once dirname( __DIR__ ) . '/Rest/functions.php';

/** @covers \Saltus\WP\Framework\Features\AiAssistant\AiAssistantProvider */
/** @covers \Saltus\WP\Framework\Rest\AiAssistantController */
class AiAssistantTest extends TestCase {

	protected function setUp(): void {
		global $wp_filters_registered, $wp_filter_values, $wp_rest_routes_registered, $wp_posts, $wp_current_user_can;
		global $wp_ai_supported, $wp_ai_supported_for_text, $wp_ai_text_result, $wp_ai_generated;
		$wp_filters_registered = [];
		$wp_filter_values     = [];
		$wp_rest_routes_registered = [];
		$wp_posts             = [];
		$wp_current_user_can  = true;
		// Default to the pre-WordPress 7.0 contract; tests opt in to the AI client.
		$wp_ai_supported          = false;
		$wp_ai_supported_for_text = null;
		$wp_ai_text_result        = null;
		$wp_ai_generated          = [];
	}

	public function testConfiguredModelExposesActionsAndNormalizedFields(): void {
		$provider = new AiAssistantProvider( $this->modeler() );
		$definition = $provider->definition( 'book' );

		$this->assertIsArray( $definition );
		$this->assertSame( 'book', $definition['model'] );
		$this->assertContains( 'improve_title', array_column( $definition['actions'], 'name' ) );
		$this->assertSame( 'subtitle', $definition['fields'][0]['path'] );
	}

	public function testDispatchesThroughProviderFilterAndNormalizesOutput(): void {
		add_filter(
			'saltus/framework/ai/assistant_actions',
			static function ( $value, string $action, array $payload ): array {
				return [ 'target' => 'post_title', 'value' => strtoupper( $payload['title'] ), 'suggestions' => [ 'One', 12 ] ];
			},
			10,
			7
		);
		$provider = new AiAssistantProvider( $this->modeler() );
		$result = $provider->dispatch( 'book', 'improve_title', [ 'title' => 'A book' ] );

		$this->assertSame( 'improve_title', $result['action'] );
		$this->assertSame( 'A BOOK', $result['value'] );
		$this->assertSame( [ 'One' ], $result['suggestions'] );
	}

	public function testUnknownActionAndMissingProviderReturnErrors(): void {
		$provider = new AiAssistantProvider( $this->modeler() );
		$this->assertSame( 'ai_assistant_action_invalid', $provider->dispatch( 'book', 'unknown', [] )->get_error_code() );
		$this->assertSame( 'ai_assistant_no_provider', $provider->dispatch( 'book', 'improve_title', [] )->get_error_code() );
		$this->assertNull( $provider->definition( 'missing' ) );
	}

	public function testControllerRegistersActionRouteAndChecksPostPermissions(): void {
		$modeler = $this->modeler();
		$controller = new AiAssistantController( new ModelRestPolicy( $modeler ), new AiAssistantProvider( $modeler ) );
		$controller->register_routes();

		$this->assertCount( 1, $GLOBALS['wp_rest_routes_registered'] );
		$this->assertStringContainsString( '/ai-assistant/', $GLOBALS['wp_rest_routes_registered'][0]['route'] );
		$request = new \WP_REST_Request( [ 'post_type' => 'book', 'post_id' => 0 ] );
		$this->assertTrue( $controller->permissions_check( $request ) );

		$GLOBALS['wp_current_user_can'] = false;
		$this->assertSame( 'rest_forbidden', $controller->permissions_check( $request )->get_error_code() );
	}

	public function testControllerRejectsMissingAndMismatchedPosts(): void {
		$modeler   = $this->modeler();
		$controller = new AiAssistantController( new ModelRestPolicy( $modeler ), new AiAssistantProvider( $modeler ) );
		$missing = new \WP_REST_Request( [ 'post_type' => 'book', 'post_id' => 12 ] );
		$this->assertSame( 'ai_assistant_post_not_found', $controller->permissions_check( $missing )->get_error_code() );

		$GLOBALS['wp_posts'][12] = new \WP_Post( [ 'ID' => 12, 'post_type' => 'movie' ] );
		$this->assertSame( 'ai_assistant_post_type_mismatch', $controller->permissions_check( $missing )->get_error_code() );
	}

	public function testFilterResultStillWinsOverTheAiClient(): void {
		global $wp_ai_supported, $wp_ai_text_result, $wp_ai_generated;
		$wp_ai_supported   = true;
		$wp_ai_text_result = 'Generated by the client';
		add_filter(
			'saltus/framework/ai/assistant_actions',
			static function (): array {
				return [ 'value' => 'From the plugin filter' ];
			},
			10,
			7
		);

		$result = ( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'improve_title', [ 'title' => 'A book' ] );

		$this->assertSame( 'From the plugin filter', $result['value'] );
		$this->assertSame( [], $wp_ai_generated, 'The AI client must not be called when a filter handled the action.' );
	}

	public function testGeneratesTextThroughTheAiClientWhenNoFilterHandlesTheAction(): void {
		global $wp_ai_supported, $wp_ai_text_result, $wp_ai_generated;
		$wp_ai_supported   = true;
		$wp_ai_text_result = "  A Better Book Title  ";

		$result = ( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'improve_title', [ 'title' => 'A book', 'content' => 'Chapter one.' ] );

		$this->assertSame( 'A Better Book Title', $result['value'], 'Generated text should be trimmed.' );
		$this->assertSame( 'post_title', $result['target'] );
		$this->assertCount( 1, $wp_ai_generated );
		$this->assertStringContainsString( 'A book', $wp_ai_generated[0]['prompt'] );
	}

	public function testJsonActionReturnsSuggestionsAndAppliesContextAsSystemInstruction(): void {
		global $wp_ai_supported, $wp_ai_text_result, $wp_ai_generated;
		$wp_ai_supported   = true;
		$wp_ai_text_result = '["fiction","classics",7]';

		$result = ( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'suggest_terms', [ 'content' => 'A novel.' ] );

		$this->assertSame( [ 'fiction', 'classics' ], $result['suggestions'], 'Non-string entries should be dropped.' );
		$this->assertSame( 'terms', $result['target'] );
		$this->assertSame( [ 'type' => 'array', 'items' => [ 'type' => 'string' ] ], $wp_ai_generated[0]['config']['schema'] );
		$this->assertStringContainsString( 'Clear and factual', $wp_ai_generated[0]['config']['system_instruction'] );
	}

	public function testClientErrorsPropagateWithTheirStatus(): void {
		global $wp_ai_supported, $wp_ai_text_result;
		$wp_ai_supported   = true;
		$wp_ai_text_result = new \WP_Error( 'prompt_network_error', 'Upstream unreachable', [ 'status' => 503 ] );

		$result = ( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'summarize', [ 'content' => 'Text.' ] );

		$this->assertSame( 'prompt_network_error', $result->get_error_code() );
		$this->assertSame( 503, $result->get_error_data()['status'] );
	}

	public function testUnsupportedCapabilityAndMalformedJsonAreReportedDistinctly(): void {
		global $wp_ai_supported, $wp_ai_supported_for_text, $wp_ai_text_result;
		$wp_ai_supported = true;

		$wp_ai_supported_for_text = false;
		$unsupported              = ( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'summarize', [ 'content' => 'Text.' ] );
		$this->assertSame( 'ai_assistant_unsupported', $unsupported->get_error_code() );

		$wp_ai_supported_for_text = true;
		$wp_ai_text_result        = 'not json at all';
		$malformed                = ( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'suggest_terms', [ 'content' => 'Text.' ] );
		$this->assertSame( 'ai_assistant_invalid_json', $malformed->get_error_code() );

		$wp_ai_text_result = '   ';
		$empty             = ( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'summarize', [ 'content' => 'Text.' ] );
		$this->assertSame( 'ai_assistant_empty_result', $empty->get_error_code() );
	}

	public function testPromptBuilderFilterCanPinAProvider(): void {
		global $wp_ai_supported, $wp_ai_text_result, $wp_ai_generated;
		$wp_ai_supported   = true;
		$wp_ai_text_result = 'Summary.';
		add_filter(
			'saltus/framework/ai/prompt_builder',
			static function ( $builder ) {
				return $builder->using_provider( 'anthropic' );
			},
			10,
			4
		);

		( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'summarize', [ 'content' => 'Text.' ] );

		$this->assertSame( 'anthropic', $wp_ai_generated[0]['config']['provider'] );
	}

	public function testFallsBackToPostFieldsWhenPayloadOmitsThem(): void {
		global $wp_ai_supported, $wp_ai_text_result, $wp_ai_generated, $wp_posts;
		$wp_ai_supported     = true;
		$wp_ai_text_result   = 'Summary.';
		$wp_posts[9]         = new \WP_Post( [ 'ID' => 9, 'post_type' => 'book', 'post_title' => 'Stored Title', 'post_content' => 'Stored body.' ] );

		( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'summarize', [ 'post_id' => 9 ] );

		$this->assertStringContainsString( 'Stored Title', $wp_ai_generated[0]['prompt'] );
		$this->assertStringContainsString( 'Stored body.', $wp_ai_generated[0]['prompt'] );
	}

	public function testWithoutTheAiClientDispatchKeepsThePreWordPress7Contract(): void {
		global $wp_ai_supported;
		$wp_ai_supported = false;

		$result = ( new AiAssistantProvider( $this->modeler() ) )->dispatch( 'book', 'improve_title', [ 'title' => 'A book' ] );

		$this->assertSame( 'ai_assistant_no_provider', $result->get_error_code() );
		$this->assertSame( 501, $result->get_error_data()['status'] );
	}

	/** @return Modeler */
	private function modeler(): Modeler {
		$model = $this->createStub( Model::class );
		$model->method( 'get_name' )->willReturn( 'book' );
		$model->method( 'get_type' )->willReturn( 'post_type' );
		$model->method( 'get_config' )->willReturn(
			[
				'ai_context' => [
					'brand_voice' => 'Clear and factual, no hype.',
					'field_rules' => [],
				],
			]
		);
		$model->method( 'get_options' )->willReturn( [ 'show_in_rest' => true ] );
		$model->method( 'get_args' )->willReturn( [ 'meta' => [ 'box' => [ 'fields' => [ 'subtitle' => [ 'type' => 'text' ] ] ] ] ] );
		$modeler = $this->createStub( Modeler::class );
		$modeler->method( 'get_models' )->willReturn( [ 'book' => $model ] );
		return $modeler;
	}
}
