<?php
/**
 * Generated by bin/generate-asset-manifests.mjs. Do not edit.
 *
 * Re-run `npm run assets:manifest` after editing the assets this versions.
 */
return [
	'dependencies' => [ 'wp-element', 'wp-i18n' ],
	'version'      => 'be1e574798c6af9e0047',
];
